name: RAPZ AW DASHBOARD

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyTelegramBotAPI pycryptodome requests urllib3

      - name: Run Generator
        run: |
          # Timeout 5 jam (18000s) biar aman dari limit GitHub
          timeout 18000s python bot.py || echo "Selesai/Limit reached"

      - name: Create Web Dashboard
        run: |


      - name: Save and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "AW-Deployer"
          git add .
          git commit -m "Auto-Gen AW: $(date)" || echo "No changes"
          git push
